server:
  port: 8082

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
