server:
  port: 8082

spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      file-size-threshold: 1KB

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
